### ISSUE TITLE
Build vertical menu (skeleton and styling)

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#14]
@damirius Under this issue, you will create the view representing the vertical menu that we will use on the product page. 

It includes building the HTML and styling it so it follows the guidelines described in #9.

Let me know if you have questions.

**Comment by WebDevJL** [comment]
@damirius Adding the description from #9 here as specifications:

Every page will have the top menu. It is a menu of few items. On the run, we will have Home, My Account, My Basket, Contact. For now we will have Home and Contact. The issue to build this is not yet created.

For the product page only, you will build a vertical menu (made of numbers now but icons later). It will allow to navigate through the section of the product as show in the mockup. 
You are free to choose from either:

loading all the product contents onto a single page
or loading each section as a unique page load.
I would prefer the first but if it is too complex, do the second.

If doing the first, when you click on each number in the menu, it will scroll down or up to the selected section in the same way showcased in the template design when you click on one of the top menu link.

Anyhow, the vertical menu will remain center vertically based on the heigh of the viewport. Can you achieve that?

Important: only build 6 buttons in this menu. Because space will be limited on smartphones, I suggested to the PM to stick to 6 sections max.

**Comment by damirius** [comment]
@WebDevJL 

New stuff is on feature_product_page branch, some css coding issues should be fixed, vertical menu should be added to the product page with placeholder glyphicons. It uses scrollspy to track current section and also uses smooth scrolling. I also worked with html skeleton a bit since I was testing the page template on my Nexus 5 to see how it looks on mobile.

I'll wait for your response on the #4 issue regarding number of sections and which sections should we keep. Once we see what to do with that I can change the links on the menu and set it up.

**Comment by WebDevJL** [comment]
@damirius 

It seems I can't see the result even though I am on the feature. I see the views get.html.twig, vertical.hmtl.twig and the layout.html.twig but it doesn't seem to be loading.

I still see only the "Product display 1" text. Any ideas?

**Comment by damirius** [comment]
@WebDevJL 

Hm, if you see views and css/js in public directory that's it.
Run `php bin/console asset:install --symlink` to install symlinks to css/js. That will only help with css/js.
For your problem I presume you are running the app in production environment, if that's the case, production is hard caching most of things, so try running `php bin/console cache:clear --env=prod`

**Comment by WebDevJL** [comment]
@damirius I got it working. I will review the work. I see that I missed to mention a few details.

**Comment by WebDevJL** [comment]
@damirius It can see the vertical menu. However the section are too small to make it work fine. I will update them to be much higher and we will take take of styling after. Thanks for your work.
